class Matematica {
  static const Map<String, Map<String, List<String>>> cursos = {
    'Matemática Básica': {
      'Frações': [
        'O que é uma fração?',
        'O significado de uma fração',
        'Como se lê uma fração, classificação das frações',
        'Frações equivalentes',
        'Números fracionários',
        'Adição e subtração de números fracionários',
        'Multiplicação e divisão de números fracionários',
        'Potenciação e radiciação de números fracionários',
      ],
      'Divisibilidade': [
        'Critérios de divisibilidade',
        'Números primos',
        'Decomposição em fatores primos',
        'Determinação dos divisores de um número',
        'Máximo divisor comum (M.D.C.)',
        'Mínimo múltiplo comum (M.M.C.)',
      ],
      'Equações do 1º grau com uma variável': [
        'Introdução',
        'Conjunto universo e conjunto verdade de uma equação',
        'Raízes de uma equação',
        'Resolução de uma equação',
        'Equações impossíveis e identidades',
      ],
      'Equações do 1º grau com duas variáveis': [
        'Pares ordenados',
        'Coordenadas cartesianas',
        'Plano cartesiano',
        'Produto cartesiano',
        'O que é uma equação do 1º grau com duas variáveis?',
        'Solução de uma equação do 1º grau com duas variáveis',
        'Gráfico de uma equação do 1º grau com duas variáveis',
        'Sistemas de equações',
        'Resolução de Sistemas',
      ],
      'Inequações do 1º grau': [
        'O que é uma inequação?',
        'Representação gráfica',
        'Resolução gráfica de um sistema de inequações',
      ],
      'Potenciação': [
        'O que é potenciação?',
        'Propriedades da potenciação',
        'Produto de potências de mesma base',
        'Divisão de potências de mesma base',
        'Potência da potência',
        'Distributiva em relação à multiplicação',
        'Distributiva em relação à divisão',
      ],
      'Radiciação': [
        'O que é radiciação?',
        'Raízes de índice par',
        'Raízes de índice ímpar',
        'Potência com expoente fracionário',
        'Propriedades dos radicais',
        'Simplificação de radicais',
        'Radicais semelhantes',
        'Adição e subtração de radicais',
        'Multiplicação e divisão de radicais',
        'Potência de um radical',
        'Radical de um radical',
        'Racionalização de denominadores',
      ],
      'Razões': [
        'O que é uma razão?',
        'Termos de uma razão',
        'Razões inversas',
        'Razões equivalentes',
        'Razões entre grandezas da mesma espécie',
        'Razões entre grandezas de espécies diferentes',
      ],
      'Proporções': [
        'O que é uma proporção?',
        'Elementos de uma proporção',
        'Propriedade fundamental das proporções',
        'Aplicações da propriedade fundamental',
        'Quarta proporcional',
        'Proporção contínua',
        'Propriedades das proporções',
        'Proporção múltipla',
      ],
      'Algarismos romanos': [
        'Numeração romana e suas regras',
        'Tabela - de 1 a 1449',
        'Tabela - de 1450 a 2100',
        'Números maiores que 2100',
      ],
      'Grandezas proporcionais': [
        'O que é uma grandeza?',
        'Grandezas diretamente proporcionais',
        'Grandezas inversamente proporcionais',
      ],
      'Regra de três': [
        'Regra de três simples',
        'Regra de três composta',
      ],
      'Dízimas periódicas': [
        'Dízimas periódicas',
        'Geratriz de uma dízima periódica',
      ],
      'Porcentagem': [
        'Porcentagem e razão centesimal',
        'Fator de Multiplicação',
      ],
      'Números decimais': [
        'Numeração decimal',
        'Frações decimais',
        'Leitura dos números decimais',
        'Transformação de números decimais em frações decimais e vice-versa',
        'Decimais equivalentes, Comparação de decimais',
      ],
      'Médias': [
        'Média aritmética simples',
        'Média ponderada',
      ],
      'Números racionais': [
        'O que é um número racional?',
        'Conjunto dos números racionais e seus subconjuntos',
        'Operações com números racionais',
      ],
      'Tabelas': [
        'Tabuada dos números de 1 a 10',
        'Tabela de números árabes, cardinais e ordinais',
      ],
      'Operações com números racionais decimais': [
        'Adição e Subtração',
        'Multiplicação',
        'Divisão exata',
        'Divisão não exata',
        'Representação decimal de uma fração ordinária',
        'Potenciação e raiz quadrada',
        'Expressões numéricas',
      ],
      'Ângulos': [
        'O ângulo e os seus elementos',
        'Ângulo nulo e ângulo raso',
        'Medida de um ângulo',
        'Usando o transferidor',
        'Leitura de um ângulo',
        'Questões envolvendo medidas de ângulos',
        'Transformação de unidades',
        'Transformando em número misto',
        'Operações (adição e subtração)',
        'Operações (multiplicação e divisão por número natural)',
        'Ângulos congruentes',
        'Ângulos consecutivos',
        'Ângulos adjacentes',
        'Bissetriz de um ângulo',
        'Ângulo agudo, obtuso e reto',
        'Ângulos complementares',
        'Ângulos suplementares',
        'Ângulos opostos pelo vértice',
      ],
      'Teoria dos Conjuntos': [
        'Introdução e símbolos',
        'Símbolos das operações',
        'Conceitos de conjuntos',
      ],
    },
    'Geometria': {
      'Geometria plana': [
        'Áreas das figuras planas',
        'Polígonos',
      ],
      'Medidas de superfície': [
        'Introdução, Superfície e área, Metro quadrado',
        'Transformação de unidades',
      ],
      'Medidas de volume': [
        'Introdução, Metro cúbico',
        'Transformação de unidades',
      ],
      'Medidas de capacidade': [
        'Introdução, capacidade e litro',
        'Transformação de unidades',
      ],
      'Medidas de massa': [
        'Introdução, Quilograma',
        'Leitura das medidas de massa',
        'Transformação de unidades',
      ],
      'Medidas de tempo': [
        'Introdução, Segundo, Múltiplos do segundo',
        'Outras unidades de medida',
      ],
      'Medidas de comprimento': [
        'Sistema métrico decimal, metro',
        'Leitura das medidas de comprimento',
        'Transformação de unidades',
        'Perímetro de polígonos',
        'Comprimento da circunferência',
      ],
      'Quadriláteros': [
        'Definição, elementos, côncavos e convexos',
        'Soma das medidas dos ângulos internos',
        'Quadriláteros notáveis - paralelogramo',
        'Retângulo, losango, quadrado e trapézio',
        'Trapézio retângulo, isósceles e escaleno',
        'Propriedades dos paralelogramos',
      ],
      'Semelhança de Polígonos': [
        'Introdução',
        'Polígonos semelhantes',
        'Propriedades da semelhança de polígonos',
      ],
      'Geometria espacial': [
        'Pontos, retas e planos',
        'Axiomas',
        'Posições relativas de duas retas',
        'Determinação de um plano',
        'Posições relativas de reta e plano',
        'Perpendicularismo entre reta e plano',
        'Posições relativas de dois planos',
        'Projeção ortogonal',
        'Distâncias entre ponto, reta e planos',
        'Ângulos entre retas e planos',
        'Diedros, triedos, poliedros',
        'Poliedros',
        'Poliedros regulares',
        'Prismas',
        'Classificação dos prismas',
        'Secção do prisma',
        'Paralelepípedo',
        'Cubo',
        'Generalização do volume de um prisma',
        'Cilindro',
        'Secções do cilindro',
        'Área e volume do cilindro',
        'Cilindro equilátero',
        'Cone circular',
        'Área e volume do cone',
        'Pirâmide',
        'Secção paralela à base de uma pirâmide',
        'Área e volume da pirâmide',
        'Tronco de pirâmide',
        'Tronco de cone',
        'Esfera',
        'Partes da esfera',
      ],
      'Geometria analítica - Retas': [
        'Introdução',
        'Plano cartesiano',
        'Distância entre dois pontos',
        'Razão de secção',
        'Ponto médio',
        'Baricentro de um triângulo',
        'Condições de alinhamento de três pontos',
        'Equação geral',
        'Equação segmentária',
        'Equações paramétricas',
        'Equação reduzida',
        'Coeficiente angular',
        'Representação gráfica de retas',
        'Posições relativas entre retas',
        'Ângulo entre duas retas',
        'Distância entre ponto e reta',
        'Bissetrizes',
      ],
      'Geometria analítica - Circunferência': [
        'Circunferência',
        'Determinação do centro e do raio',
        'Posição de um ponto em relação a uma circunferência',
        'Posição de uma reta em relação a uma circunferência',
        'Condições de tangência entre reta e circunferência',
      ],
      'Geometria analítica - Cônicas': [
        'Introdução',
        'Elipse',
        'Equações da elipse',
        'Hipérbole',
        'Equações da hipérbole',
        'Hipérbole equilátera',
        'Parábola',
        'Equações da parábola',
        'Continua após a publicidade',
      ],
    },
    'Álgebra': {
      'Equações do 2º grau': [
        'O que é uma equação do 2º grau?',
        'Raízes de uma equação do 2º grau',
        'Resolução de equações incompletas',
        'Resolução de equações completas',
        'Discriminante',
        'Equações literais',
        'Relações entre os coeficientes e as raízes',
        'Composição de uma equação de 2º grau',
        'Forma fatorada',
        'Equações biquadradas',
        'Resolução de uma equação biquadrada',
        'Composição da equação biquadrada',
        'Equações irracionais',
        'Sistemas de equações do 2º grau',
        'Problemas do 2º grau',
        'Outros exemplos',
      ],
      'Análise Combinatória': [
        'Introdução',
        'Fatorial de um número',
        'Arranjo simples',
        'Permutação simples',
        'Combinação simples',
      ],
      'Vetores': [
        'Reta e segmento orientado',
        'Direção e sentido',
        'Segmentos equipolentes',
        'O que é um vetor?',
        'Alguns tipos de vetores',
        'Vetores colineares',
        'Vetores coplanares',
        'Operações com vetores',
        'Produto escalar',
      ],
      'Funções': [
        'O que é uma função',
        'Domínio e imagem de uma função',
        'Obtenção do domínio',
        'Construção do gráfico cartesiano',
        'Raízes de uma função',
        'Propriedades de uma função',
        'Função par e função ímpar',
        'Funções crescente e decrescente',
        'Função composta',
        'Função inversa',
      ],
      'Polinômios': [
        'Definição, grau de um polinômio, valor numérico',
        'Raiz de um polinômio',
        'Polinômios idênticos',
        'Operações com polinômios',
        'Divisão de polinômios',
        "Teorema do resto e Teorema de D'Alembert",
        'Divisão de um polinômio por (x-a)(x-b)',
        'Dispositivo de Briot-Ruffini',
        'Divisões sucessivas',
        'Equações polinomiais',
        'Multiplicidade de uma raiz',
        'Raízes nulas, complexas e racionais',
        'Relações de Girard',
      ],
      'Produtos notáveis': [
        'Exercícios resolvidos e comentados',
      ],
      'Progressões': [
        'Sequências',
        'Progressão aritmética',
        'Fórmula do termo geral de uma PA',
        'Soma dos n termos de uma PA',
        'Progressão geométrica',
        'Soma dos n primeiros termos de uma PG',
        'Soma dos termos de uma PG infinita',
      ],
      'Binômio de Newton': [
        'Introdução',
        'Coeficientes binomiais',
        'Triângulo de Pascal',
        'Propriedades do triângulo de Pascal',
        'Fórmula do desenvolvimento',
        'Fórmula do termo geral',
      ],
      'Função do 1º grau ou função afim': [
        'Introdução',
        'Zero ou raiz da função',
        'Função crescente ou decrescente',
        'Sinal da função',
      ],
      'Função quadrática': [
        'Definição e gráfico',
        'Zeros ou raízes',
        'Coordenadas do vértice da parábola',
        'Construção da parábola',
        'Sinal da função',
      ],
      'Sistemas lineares': [
        'Introdução',
        'Matrizes associadas a um sistema linear',
        'Sistemas homogêneos',
        'Classificação de um sistema quanto ao número de soluções',
        'Discussão de um sistema linear',
        'Sistemas equivalentes',
        'Sistemas escalonados',
        'Sistemas escalonados (continuação)',
      ],
      'Matrizes': [
        'Introdução',
        'Notação geral',
        'Matriz linha, coluna e quadrada',
        'Matriz nula, diagonal e identidade',
        'Matriz transposta, simétrica e oposta',
        'Adição e subtração de matrizes',
        'Multiplicação de um número real por uma matriz',
        'Multiplicação de matrizes',
      ],
      'Determinantes': [
        'Introdução',
        'Menor complementar',
        'Cofator',
        'Teorema de Laplace',
        'Regra de Sarrus',
        'Propriedades dos determinantes',
        'Propriedades (parte 2)',
        'Propriedades (parte 3)',
      ],
      'Números complexos': [
        'Introdução e forma algébrica',
        'Igualdade de números complexos',
        'Conjugado de um número complexo',
        'Adição e subtração na forma algébrica',
        'Multiplicação e divisão na forma algébrica',
        'Potências de i',
        'Módulo e argumento',
        'Forma trigonométrica ou polar',
        'Multiplicação e divisão na forma trigonométrica',
        'Potenciação e radiciação na forma trigonométrica',
      ],
      'Conjuntos numéricos': [
        'Material sobre os conjuntos numéricos',
      ],
    },
    'Trigonometria': {
      'Razões trigonométricas': [
        'Catetos e hipotenusas',
        'Seno e cosseno',
        'Tangente',
        'As razões trigonométricas de 30º, 45º e 60º',
      ],
      'Trigonometria': [
        'Arquivo com fórmulas de trigonometria',
      ],
      'Equações trigonométricas': [
        'Introdução',
        'Resolução da 1ª equação fundamental',
        'Resolução da 3ª equação fundamental',
      ],
      'Inequações trigonométricas': [
        'Introdução',
        'Resolução das inequações (parte 1)',
        'Resolução das inequações (parte 2)',
      ],
    },
    'Cálculo': {
      'Limites': [
        'Noção intuitiva de limite',
        'Propriedades dos Limites',
        'Limites Laterais, Continuidade',
        'Limites envolvendo infinito',
        'Limites trigonométricos',
        'Limites exponenciais',
      ],
      'Derivadas': [
        'Reta Tangente',
        'O que é derivada?',
        'Regra da cadeia e derivada de funções inversas',
        'Derivadas de funções trigonométricas',
        'Derivadas das funções exponencial e logarítmica',
        'Derivadas das funções hiperbólicas',
        'Derivadas de alta ordem',
      ],
      'Integrais': [
        'Integrais indefinidas',
        'Integrais definidas',
        'Integrais definidas (continuação)',
        'Integrais definidas (exemplo)',
        'Cálculo da integral definida',
        'Princípio do cálculo de integrais',
        'Fórmulas de integração',
        'Integração por partes',
        'Integração por partes para integrais definidas',
        'Fórmulas de redução',
        'Integrais trigonométricas',
      ],
      'Equações diferenciais': [
        'Definição e classificação',
        'Equações lineares homogêneas, 2ª ordem',
        'Equações diferenciais lineares de ordem N',
      ],
      'Funções logarítmica e exponencial': [
        'Funções inversas',
        'Domínio e imagem das funções inversas',
        'Gráficos das funções inversas',
        'Funções logarítmica e exponencial',
        'Logaritmos',
        'Funções logarítmicas',
        'Funções definidas explicitamente e implicitamente',
        'Diferenciação implícita',
        'Derivadas de potências racionais de x',
        'Derivadas de funções logarítmicas',
        'Diferenciação logarítmica',
        'Derivadas de funções exponenciais',
        'Derivadas das funções trigonométricas inversas',
      ],
      'Séries e sequências': [
        'Sequências e Teorema do Sanduíche',
        'Séries',
        'Série Geométrica',
        'Série-P, série alternada e série de potência',
        'Teste de Leibniz',
        'Teste de D´Alembert, Convergência absoluta',
        'Resumo sobre séries',
      ],
      'Função exponencial': [
        'Material para o estudo da função exponencial',
      ],
      'Função logarítmica': [
        'Material para o estudo da função logarítmica',
      ],
      'Função modular': [
        'Material para o estudo da função modular',
      ],
    },
    'Outros': {
      'Probabilidade': [
        'Introdução',
        'Probabilidade condicional',
        'Eventos independentes',
        'Probabilidade da união de eventos',
      ],
      'Logaritmos': [
        'Definição',
        'Propriedades operatórias',
        'Cologaritmo',
        'Mudança de base',
        'Cálculo on-line de logaritmos',
      ],
      'Tabelas Avançadas': [
        'Tabela trigonométrica',
        'Tabela de logaritmos (base 2 a 9)',
        'Tabela de logaritmos decimais',
      ],
      'Matemática Financeira': [
        'Conceitos básicos',
        'Juros simples',
        'Juros compostos',
        'Relação entre juros e progressões',
        'Taxas equivalentes',
        'Taxas nominais',
        'Taxas efetivas',
        'Fluxo de caixa',
        'Valor presente e valor futuro',
      ],
    },
  };
}
