// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPOO03OQwROqzvpdTKRLPwYvESoolCxaU',
    appId: '1:11203362979:web:e554fe79d8d9c0a53cff16',
    messagingSenderId: '11203362979',
    projectId: 'mathquest6969',
    authDomain: 'mathquest6969.firebaseapp.com',
    storageBucket: 'mathquest6969.firebasestorage.app',
    measurementId: 'G-H1LP834P4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ZTYE2iOnTVUlXlN0O2Xy6lBpbh-TwE8',
    appId: '1:11203362979:android:955c82a65d5579843cff16',
    messagingSenderId: '11203362979',
    projectId: 'mathquest6969',
    storageBucket: 'mathquest6969.firebasestorage.app',
  );
}