// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPOO03OQwROqzvpdTKRLPwYvESoolCxaU',
    appId: '1:11203362979:web:e554fe79d8d9c0a53cff16',
    messagingSenderId: '11203362979',
    projectId: 'mathquest6969',
    authDomain: 'mathquest6969.firebaseapp.com',
    storageBucket: 'mathquest6969.firebasestorage.app',
    measurementId: 'G-H1LP834P4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2ZTYE2iOnTVUlXlN0O2Xy6lBpbh-TwE8',
    appId: '1:11203362979:android:955c82a65d5579843cff16',
    messagingSenderId: '11203362979',
    projectId: 'mathquest6969',
    storageBucket: 'mathquest6969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi4ZXQWg0bFXNP0bCqv-3wC9Hdh_nz-Ds',
    appId: '1:11203362979:ios:2f516bed80f323bb3cff16',
    messagingSenderId: '11203362979',
    projectId: 'mathquest6969',
    storageBucket: 'mathquest6969.firebasestorage.app',
    iosBundleId: 'com.example.mathquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi4ZXQWg0bFXNP0bCqv-3wC9Hdh_nz-Ds',
    appId: '1:11203362979:ios:2f516bed80f323bb3cff16',
    messagingSenderId: '11203362979',
    projectId: 'mathquest6969',
    storageBucket: 'mathquest6969.firebasestorage.app',
    iosBundleId: 'com.example.mathquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPOO03OQwROqzvpdTKRLPwYvESoolCxaU',
    appId: '1:11203362979:web:5617f62eccf3da043cff16',
    messagingSenderId: '11203362979',
    projectId: 'mathquest6969',
    authDomain: 'mathquest6969.firebaseapp.com',
    storageBucket: 'mathquest6969.firebasestorage.app',
    measurementId: 'G-BD9GYDSQSR',
  );

}